language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "boroda4436"
    token:
      secure: "0049297c1405b0f4be272bf484ba5ce92e3f9d0b" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
